### ISSUE TITLE
Playback on other websites has been disabled by the video owner

### ISSUE THREAD

**Issue by kaktux** [kevinpapst/freshrss-youtube#10]
Hi there,

with every feed i try i get the error "Playback on other websites has been disabled by the video owner".
I guess this is due to youtube settings of the video owner.
Is there any workaround for this??

**Comment by kevinpapst** [comment]
I suffer from that as well, even though I just have it for certain channels. 
Most of my subscriptions work flawless in FreshRSS and the native clients I use via the FreshRSS API, e.g this one: https://www.youtube.com/feeds/videos.xml?channel_id=UCYq-iAOSZBvoUxvfzwKIZWA

There is no workaround that I know of ... I guess otherwise Youtube would be in some sort of trouble.

**Comment by kevinpapst** [comment]
Not possible to fix, closing.
